#!/bin/sh
set -eu

################################################################################
# Ensure .rst confirm to writegood
################################################################################

readonly DEBUG=${DEBUG:-unset}
if [ "${DEBUG}" != unset ]; then
  set -x
fi

write-good "$@"
